// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Poengrenn.DAL.Models;

#nullable disable

namespace Poengrenn.DAL.Migrations
{
    [DbContext(typeof(PoengrennContext))]
    partial class PoengrennContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Poengrenn.DAL.Models.Konkurranse", b =>
                {
                    b.Property<int>("KonkurranseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("KonkurranseID"));

                    b.Property<DateTime?>("Dato")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Navn")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Serie")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("StartInterval")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TypeID")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("KonkurranseID");

                    b.HasIndex("TypeID");

                    b.ToTable("Konkurranse", (string)null);
                });

            modelBuilder.Entity("Poengrenn.DAL.Models.KonkurranseDeltaker", b =>
                {
                    b.Property<int>("KonkurranseID")
                        .HasColumnType("integer");

                    b.Property<string>("KlasseID")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("PersonID")
                        .HasColumnType("integer");

                    b.Property<string>("BetalingsNotat")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool?>("Betalt")
                        .HasColumnType("boolean");

                    b.Property<int?>("LagNummer")
                        .HasColumnType("integer");

                    b.Property<TimeSpan?>("SluttTid")
                        .HasColumnType("interval");

                    b.Property<int?>("StartNummer")
                        .HasColumnType("integer");

                    b.Property<TimeSpan?>("StartTid")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("Tidsforbruk")
                        .HasColumnType("interval");

                    b.Property<bool?>("Tilstede")
                        .HasColumnType("boolean");

                    b.Property<string>("TypeID")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("KonkurranseID", "KlasseID", "PersonID");

                    b.HasIndex("PersonID");

                    b.HasIndex("KlasseID", "TypeID");

                    b.ToTable("KonkurranseDeltaker", (string)null);
                });

            modelBuilder.Entity("Poengrenn.DAL.Models.KonkurranseKlasse", b =>
                {
                    b.Property<string>("KlasseID")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TypeID")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("DistanseKm")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("ForsteStartnummer")
                        .HasColumnType("integer");

                    b.Property<string>("Kjonn")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("MaxAlder")
                        .HasColumnType("integer");

                    b.Property<bool>("MedTidtaking")
                        .HasColumnType("boolean");

                    b.Property<int>("MinAlder")
                        .HasColumnType("integer");

                    b.Property<string>("Navn")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SisteStartnummer")
                        .HasColumnType("integer");

                    b.HasKey("KlasseID", "TypeID");

                    b.HasIndex("TypeID");

                    b.ToTable("KonkurranseKlasse", (string)null);
                });

            modelBuilder.Entity("Poengrenn.DAL.Models.KonkurranseType", b =>
                {
                    b.Property<string>("TypeID")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("Aktiv")
                        .HasColumnType("boolean");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("StandardAntallKonkurranser")
                        .HasColumnType("integer");

                    b.HasKey("TypeID");

                    b.ToTable("KonkurranseType", (string)null);

                    b.HasData(
                        new
                        {
                            TypeID = "1",
                            Aktiv = true,
                            Navn = "Telenorkarusellen",
                            StandardAntallKonkurranser = 4
                        },
                        new
                        {
                            TypeID = "2",
                            Aktiv = true,
                            Navn = "Klubbmesterskap",
                            StandardAntallKonkurranser = 1
                        });
                });

            modelBuilder.Entity("Poengrenn.DAL.Models.Person", b =>
                {
                    b.Property<int>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PersonID"));

                    b.Property<string>("Epost")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Etternavn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("Fodselsar")
                        .HasColumnType("integer");

                    b.Property<string>("Fornavn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Kjonn")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("PersonID");

                    b.ToTable("Person", (string)null);
                });

            modelBuilder.Entity("Poengrenn.DAL.Models.Konkurranse", b =>
                {
                    b.HasOne("Poengrenn.DAL.Models.KonkurranseType", "KonkurranseType")
                        .WithMany("Konkurranser")
                        .HasForeignKey("TypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KonkurranseType");
                });

            modelBuilder.Entity("Poengrenn.DAL.Models.KonkurranseDeltaker", b =>
                {
                    b.HasOne("Poengrenn.DAL.Models.Konkurranse", "Konkurranse")
                        .WithMany("KonkurranseDeltakere")
                        .HasForeignKey("KonkurranseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Poengrenn.DAL.Models.Person", "Person")
                        .WithMany("KonkurranseDeltakere")
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Poengrenn.DAL.Models.KonkurranseKlasse", "KonkurranseKlasse")
                        .WithMany("KonkurranseDeltakere")
                        .HasForeignKey("KlasseID", "TypeID");

                    b.Navigation("Konkurranse");

                    b.Navigation("KonkurranseKlasse");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Poengrenn.DAL.Models.KonkurranseKlasse", b =>
                {
                    b.HasOne("Poengrenn.DAL.Models.KonkurranseType", "KonkurranseType")
                        .WithMany("KonkurranseKlasser")
                        .HasForeignKey("TypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KonkurranseType");
                });

            modelBuilder.Entity("Poengrenn.DAL.Models.Konkurranse", b =>
                {
                    b.Navigation("KonkurranseDeltakere");
                });

            modelBuilder.Entity("Poengrenn.DAL.Models.KonkurranseKlasse", b =>
                {
                    b.Navigation("KonkurranseDeltakere");
                });

            modelBuilder.Entity("Poengrenn.DAL.Models.KonkurranseType", b =>
                {
                    b.Navigation("KonkurranseKlasser");

                    b.Navigation("Konkurranser");
                });

            modelBuilder.Entity("Poengrenn.DAL.Models.Person", b =>
                {
                    b.Navigation("KonkurranseDeltakere");
                });
#pragma warning restore 612, 618
        }
    }
}
