//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poengrenn.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KonkurranseType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KonkurranseType()
        {
            this.Konkurranser = new HashSet<Konkurranse>();
            this.KonkurranseKlasser = new HashSet<KonkurranseKlasse>();
        }
    
        public string TypeID { get; set; }
        public string Navn { get; set; }
        public int StandardAntallKonkurranser { get; set; }
        public bool Aktiv { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Konkurranse> Konkurranser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KonkurranseKlasse> KonkurranseKlasser { get; set; }
    }
}
