//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poengrenn.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KonkurranseKlasse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KonkurranseKlasse()
        {
            this.KonkurranseDeltaker = new HashSet<KonkurranseDeltaker>();
        }
    
        public string KlasseID { get; set; }
        public string TypeID { get; set; }
        public string Navn { get; set; }
        public int MinAlder { get; set; }
        public int MaxAlder { get; set; }
        public string Kjonn { get; set; }
        public int ForsteStartnummer { get; set; }
        public int SisteStartnummer { get; set; }
        public bool MedTidtaking { get; set; }
        public Nullable<decimal> DistanseKm { get; set; }
    
        public virtual KonkurranseType KonkurranseType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KonkurranseDeltaker> KonkurranseDeltaker { get; set; }
    }
}
