//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poengrenn.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KonkurranseDeltaker
    {
        public int KonkurranseID { get; set; }
        public string KlasseID { get; set; }
        public string TypeID { get; set; }
        public int PersonID { get; set; }
        public Nullable<int> StartNummer { get; set; }
        public Nullable<System.TimeSpan> StartTid { get; set; }
        public Nullable<System.TimeSpan> SluttTid { get; set; }
        public Nullable<System.TimeSpan> Tidsforbruk { get; set; }
        public Nullable<bool> Betalt { get; set; }
        public Nullable<bool> Tilstede { get; set; }
    
        public virtual Konkurranse Konkurranse { get; set; }
        public virtual KonkurranseKlasse KonkurranseKlasse { get; set; }
        public virtual Person Person { get; set; }
    }
}
