//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poengrenn.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Konkurranse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Konkurranse()
        {
            this.KonkurranseDeltakere = new HashSet<KonkurranseDeltaker>();
        }
    
        public int KonkurranseID { get; set; }
        public string Serie { get; set; }
        public string Navn { get; set; }
        public Nullable<System.DateTime> Dato { get; set; }
        public string TypeID { get; set; }
        public string Status { get; set; }
    
        public virtual KonkurranseType KonkurranseType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KonkurranseDeltaker> KonkurranseDeltakere { get; set; }
    }
}
