//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poengrenn.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            this.KonkurranseDeltakere = new HashSet<KonkurranseDeltaker>();
        }
    
        public int PersonID { get; set; }
        public string Fornavn { get; set; }
        public string Etternavn { get; set; }
        public Nullable<int> Fodselsar { get; set; }
        public string Kjonn { get; set; }
        public string Epost { get; set; }
        public string Telefon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KonkurranseDeltaker> KonkurranseDeltakere { get; set; }
    }
}
