//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poengrenn.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PoengrennSerie
    {
        public int PersonID { get; set; }
        public Nullable<bool> Betalt { get; set; }
        public Nullable<int> Poeng { get; set; }
        public int År { get; set; }
        public string Klasse { get; set; }
        public Nullable<bool> Premie { get; set; }
    }
}
