//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poengrenn.DAL.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PoengrennEntities : DbContext
    {
        public PoengrennEntities()
            : base("name=PoengrennEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Klubbmesterskap> Klubbmesterskap { get; set; }
        public virtual DbSet<Poengrenn> Poengrenn { get; set; }
        public virtual DbSet<PoengrennSerie> PoengrennSerie { get; set; }
        public virtual DbSet<Startnummere> Startnummere { get; set; }
        public virtual DbSet<Konkurranse> Konkurranse { get; set; }
        public virtual DbSet<KonkurranseDeltaker> KonkurranseDeltaker { get; set; }
        public virtual DbSet<KonkurranseType> KonkurranseType { get; set; }
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<KonkurranseKlasse> KonkurranseKlasse { get; set; }
    }
}
