//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poengrenn.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Startnummere
    {
        public Nullable<int> Startnummer { get; set; }
        public int Alder { get; set; }
        public string Kjønn { get; set; }
        public Nullable<int> FørsteStartNummer { get; set; }
        public Nullable<int> SisteStartNummer { get; set; }
        public Nullable<bool> StigendeRekkefølge { get; set; }
    }
}
